---
title: "Summary of available functionality in this package"
author: "Yang Yang"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Summary of available functionality in this package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: Summary.bib
---

This vignette shows the available functionality in this package and
gives a minial demo.

```{r, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```

```{R, eval=TRUE, echo=TRUE}
# Load the package
library(MassSpectrometry)
```

## Read the files
## Read the `mzXML` files
`mzXML` file is a common mass spectrometry data format.

```{R mzXML, eval=TRUE, echo=TRUE}
mzFns <- system.file(c("threonine/threonine_i2_e35_pH_tree.mzXML",
                       "lockmass/LockMass_test.mzXML"),
                     package = "msdata")

## Read all the mzXML data
allIntensities <- readMZ(mzFns)

## Read the peaks data within certain ragnges
starts <- c(50, 70, 80)
ends <- c(55, 75, 85)
rangedIntensities <- readMZ(mzFns, starts=starts, ends=ends)
```

## Spectrum processing
### Spectrum normalisation
We have `normaliseSpectrum` to do spectrum normalisation with three methods.

  * "sum": $$I_j = \frac{I_j}{\sum_j^n I_j}$$
  * "max": $$I_j = \frac{I_j}{\max_j^n I_j} $$
  * "unit": $$I_j = \frac{I_j}{\sqrt{\sum_j^n{I_j^2}}}$$


[@rasmussen_evaluation_1979] studied these three normalisation methods and
they found that all the normalization methods and search methods 
gave similar results, although the "sum" method seems the to be best normalization method.
  
```{R spectrumNormalisation, echo=TRUE, eval=TRUE}
x <- c(50,100,10,200)
normaliseSpectrum(x, method="sum")
normaliseSpectrum(x, method="max")
normaliseSpectrum(x, method="unit")
```

## Spectra similarity
### Euclidean geometric distance matching factor
This metric measures the geometric distance between two spectra.
The component of each spectrum is normalised into the unit length.
Then the normalised vector of spectrum can be considered as a single point 
a sphere with unit radius in a hyperspace of $n$ dimensions, 
where $n$ is the number of components of the vector.
Two closer spectra will result in smaller geometric distance [@alfassi_normalization_2004].
  
The inverse of the geometric distance plus 1 is returned in this function,
as a measure of the similarity of two spectra. 
The similarity score of two spectra between 0.5 and 1.
1 means perfect identification and 0.5 means the most dissimilarity.
This measurement is one to one correlated with cosine similarity.

$$ MF_g = \frac{1}{1 + \sum(\frac{u_i}{\sqrt{\sum{u_i^2}}} - \frac{s_i}{\sqrt{\sum{s_i^2}}})^2}$$

```{R geometricMF, echo=TRUE, eval=TRUE}
a <- c(1, 10, 5, 8)
b <- c(2, 10, 5, 8)
c <- c(1, 10, 5, 9)
geometricMF(a, b)
geometricMF(a, c)
geometricMF(b, c)
```

## Plot spectrum
### Plot a pseudo-gaussian distribution spectrum
Given a set of x (the "mass" or "mass/charge") and y (the peak "intensities"),
generate a series of points for ploting a smooth gaussian distribution spectrum.

```{R gaussianSpectrum, echo=TRUE, eval=TRUE, fig.width=5}
x <- c(100, 500, 800)
y <- c(50, 100, 20)
ans <- generatePseudoGaussianSpectrum(x, y, sd=5L, 
                                      xlim=c(1, 1000), step = 1L)
plot(ans[["x"]], ans[["y"]], type="l", xlab="m/z", ylab="Intensity")
```

## SessionInfo()
```{R sessionInfo, echo=TRUE, eval=TRUE}
sessionInfo()
```

# References